name: Org Reviewer (Reusable)

on:
  workflow_call:
    inputs:
      microservice_name:
        description: "Nombre del microservicio (default: repo name)"
        required: false
        type: string
      config_repo:
        description: "Repo de configuración (override)"
        required: false
        type: string
      rules_path:
        description: "Ruta del rules.yml"
        required: false
        type: string
        default: ".org-reviewer/rules.yml"
    secrets:
      GH_ORG_TOKEN:
        required: true
permissions:
  contents: read
  pull-requests: write
jobs:
  org-reviewer:
    name: org-reviewer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout current repo (PR HEAD)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout reviewer-workflow (central)
        uses: actions/checkout@v4
        with:
          repository: GIS-Nikolas-Demo/reviewer-workflow # <--- explícito
          path: reviewer-self
      - name: Load rules directory
        id: rules
        run: echo "RULES_PATH=reviewer-self/.org-reviewer" >> $GITHUB_OUTPUT

      - name: Parse rules to get config repo
        id: parse
        run: |
          python - << 'PY'
          import os, yaml
          from pathlib import Path

          rules_dir = os.environ.get("RULES_PATH")
          cfg_repo = "org-configs"

          # Buscar el primer archivo de reglas que tenga config_repo definido
          for f in Path(rules_dir).glob("*-rules.yml"):
              y = yaml.safe_load(open(f))
              for module, cfg in y.items():
                  if isinstance(cfg, dict) and "config_repo" in cfg:
                      cfg_repo = cfg["config_repo"]
                      break

          print(f"config repo -> {cfg_repo}")
          print(f"::set-output name=cfgrepo::{cfg_repo}")
          PY
        env:
          RULES_PATH: ${{ steps.rules.outputs.RULES_PATH }}

      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: GIS-Nikolas-Demo/org-configs
          path: config-repo
          token: ${{ secrets.GH_ORG_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install PyGithub pyyaml

      - name: Run validator
        run: python reviewer-self/.github/validator/validator.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          MICROSERVICE_NAME: ${{ inputs.microservice_name }}
          RULES_PATH: ${{ steps.rules.outputs.RULES_PATH }}
          CONFIG_REPO_DIR: config-repo
